### ISSUE TITLE
Project Wireframe

### ISSUE THREAD

**Issue by jrviray** [jrviray/cs461_admin#1]
From reading the documentation, you now have an idea of what the app is capable of. If you haven't created the sample app yet from Udemy, I suggest you go through that and then complete this task.

Your mockup does not have to super complicated, but you at least must be able to come up with what it looks like. The point of this task is, again, so that everyone is on the same page and while our ideas differ, they strive for a common goal.

Be sure to attach your completed design (as a ZIP)  in the comments section below.

**Comment by jrviray** [comment]
Upload your files here!

[example.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cae060e530f400127560ff/125516c66e82c728ace21e0d46ed8c9b2e928faccda5fd53b652fa912a5265296b51fa2e27ddb37deb1a23560b0b4cac41590916afaa807fa7a42062c80d55b98e30063e937f03a6aa8316b500bf20834c80b3ba8e49c5e83d37aa.zip)

**Comment by dipnrip** [comment]
started

**Comment by bryanjoe** [comment]
test

**Comment by dipnrip** [comment]
[landingPage.bmpr.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dbb9e7a1243b00123b40e8/125516c66e82c728ace21e0d46e49594278b8daebfe8b846ea5ffd843b046b313916ac217586f76ae5002e580a0a46ac135d584caaad897aa6b63f70de0d02eed06c4d68d47f40f2ecdd42e64bef62994597b7b5804dc5e8352ce78c87463d1d001c9bb2.zip)
